### ISSUE TITLE
服务器上没有记录播放进度

### ISSUE THREAD

**Issue by fengtan95** [alexiscn/EmbyKit#1]
作者你好，调用了public func reportSessionProgress(info: PlaybackProgressInfo) ，但是服务器上貌似不会记录播放的时长。

**Comment by alexiscn** [comment]
Please pass `isPlayback` to `false` and `autoOpenLiveStream` to `false` in getPlaybackInfo

```swift
client.getPlaybackInfo(item, startTimeTicks: startTimeTicks, isPlayback: false, autoOpenLiveStream: false)
```
